typography:
  h1:
  h2:
  h3:
  h4:
  h5:
  h6:
  p:
  body:
    font-family:
    sizes:

layout:
  banner:
  header:
  body:
  main:
  page:
  sidebar:
  sidebar_indicator:
  aside:
  footer:
  sidebar_toggler:
  sidebar_toggler_icon:

  menu_item:
    default:
    active:
    indicator:
      default:
      active:

  menu_group:
    wrapper:
    content:
    header:
      default:
      active:

common:
  icon_size:
  border_color:
  foreground_color:
  border_radius:
    sm:
    md:
    lg:
  dropdown:
    arrow_trailing_icon:
    content:
    separator:
    item:
  tab:
    class:
    outer_radius: # defaults to true
    title:
    panel:
    root:
    list:

colors:
  primary:
    DEFAULT: "#34d399"
    50: "#ecfdf5"
    100: "#d1fae5"
    200: "#a7f3d0"
    300: "#6ee7b7"
    400: "#34d399"
    500: "#10b981"
    600: "#059669"
    700: "#047857"
    800: "#065f46"
    900: "#064e3b"
    950: "#022c22"

forms:
  common:
    default_size:
    sizes:
      sm:
      md:
    border_radius:
      sm:
      md:
  button:
    variants:
      default:
      filled:
      outline:
      ghost:
      link:
